name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.4
  collection: ^1.16.0
  font_awesome_flutter: ^10.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc: ^8.0.3
  google_fonts: ^3.0.1
  intl: ^0.17.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/error/
    - assets/day/
    - assets/night/
    - assets/both/ 
